commonhelm:
  jobs:
    xbo-expenses-migrator-job:
      name: xbo-expenses-migrator
      brand: __brand__
      hook: "pre-install,pre-upgrade"
      hookWeight: "-1"
      args: ["sh", "-c", "pnpm run db:init && pnpm run db:seed"]
      deadline: 300
      image:
        repo: __docker_registry_url__/xbo-expenses-app
        tag: __xbo_expenses_app_build_version__
      variables:
        NODE_ENV: production
        DATABASE_URL: __xbo_expenses_app_dbConnection__
        SEED_ADMIN_PASSWORD: __xbo_expenses_app_seed_init_admin_password__
        DB_SSL_DISABLED: false
      secrets:
        SETTINGS_ENCRYPTION_KEY: __xbo_expenses_settings_encryption_key__
      nodeSelector:
        type: __selector_type__